steps:
  # Build the container image
  - id: "env"
    name: "bash"
    script: |
      #!/usr/bin/env bash
      printenv > .env
    env:
      - "DB_NAME=$_DB_NAME"
      - "DB_USER=$_DB_USER"
      - "DB_PASSWORD=$_DB_PASSWORD"
      - "DB_HOST=$_DB_HOST"
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/buy-me-coffee-web:$COMMIT_SHA", "."]
      # Push the container image to Container Registry
  - id: "push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/buy-me-coffee-web:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - id: "deploy"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "buy-me-coffee-web",
        "--image",
        "gcr.io/$PROJECT_ID/buy-me-coffee-web:$COMMIT_SHA",
        "--region",
        "asia-southeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "80",
        "--add-cloudsql-instances",
        "optimum-legacy-412809:asia-southeast1:buy-me-coffee",
      ]
      #options:
      #logging: CLOUD_LOGGING_ONLY
images:
  - gcr.io/$PROJECT_ID/buy-me-coffee-web
